%% run_external_current_validation_Tercan.m
% SECOND-REVISION EXTERNAL CURRENT-LIMIT VALIDATION
% TERCAN et al. PARAMETERIZATION
%
% Independent published IEEE 33-bus current limits:
%   Canonical branches 1-5 : 275 A
%       1: 1-2
%       2: 2-3
%       3: 3-4
%       4: 4-5
%       5: 5-6
%
%   Canonical branches 6-32: 120 A
%
% Source:
% Tercan, S. M.; Elma, O.; Gokalp, E.; Cali, U.
% "An expansion planning method for extending distributed energy
% system lifespan with energy storage systems."
% Energy Exploration & Exploitation, 40(2), 599-618, 2022.
% DOI: 10.1177/01445987211058304
%
% IMPORTANT:
% - Only the published branch-current limits are imported here.
% - The source-study conductor reconstruction, load-growth model,
%   ESS configuration, line-length reconstruction, and other assumptions
%   are NOT reproduced.
% - Current limits are enforced DIRECTLY in amperes.
% - They are NOT converted into author-defined MVA constraints.
% - Voltage is deliberately excluded from active-power sizing.
% - If no feasible active-only allocation exists, a minimax-current
%   diagnostic is reported rather than forcing a finite BESS size.
%
% This script must be executed using the same canonical:
%   B4P_canonical_freeze.mat
%   ieee33_data.m
%   bfs_power_flow.m
%   build_case_loads.m
%
% It does NOT overwrite the Sosnowski validation outputs.

clear;
clear functions;
clc;
rehash;

%% ========================================================================
% 0. DEPENDENCY GATE
% ========================================================================

assert(exist('B4P_canonical_freeze.mat','file') == 2, ...
    'B4P_canonical_freeze.mat not found.');

assert(exist('ieee33_data','file') == 2, ...
    'ieee33_data.m not found.');

assert(exist('bfs_power_flow','file') == 2, ...
    'bfs_power_flow.m not found.');

assert(exist('build_case_loads','file') == 2, ...
    'build_case_loads.m not found.');

assert(exist('fmincon','file') == 2, ...
    'Optimization Toolbox / fmincon is required.');

S = load('B4P_canonical_freeze.mat');

assert(isfield(S,'cfg') && isfield(S,'caseList'), ...
    'Canonical freeze must contain cfg and caseList.');

cfg = S.cfg;
caseList = S.caseList;

[busData0, branchData] = ieee33_data();

%% ========================================================================
% 1. CANONICAL NUMERICAL CONTROLS
% ========================================================================

assert(abs(cfg.baseKV - 12.66) < 1e-12, ...
    'Unexpected voltage base.');

assert(abs(cfg.Vslack - 1.05) < 1e-12, ...
    'Unexpected slack voltage.');

cfg.tol = 1e-12;
cfg.maxIter = 200;

if ~isfield(cfg,'nStarts')
    cfg.nStarts = 16;
end

if ~isfield(cfg,'fminconConstrTol')
    cfg.fminconConstrTol = 1e-9;
end

if ~isfield(cfg,'fminconOptTol')
    cfg.fminconOptTol = 1e-9;
end

if ~isfield(cfg,'fminconStepTol')
    cfg.fminconStepTol = 1e-12;
end

tauI = 1e-6;

rng(1,'twister');

%% ========================================================================
% 2. TERCAN EXTERNAL CURRENT LIMITS
% ========================================================================

nBranch = size(branchData,1);

assert(nBranch == 32, ...
    'Expected canonical IEEE 33-bus feeder with 32 branches.');

% -------------------------------------------------------------------------
% Verify that the first five canonical branches are exactly:
% 1-2, 2-3, 3-4, 4-5, 5-6
% -------------------------------------------------------------------------

expectedFirstFive = [
    1 2
    2 3
    3 4
    4 5
    5 6
    ];

assert(isequal(branchData(1:5,1:2), expectedFirstFive), ...
    ['Canonical branch ordering differs from the ordering assumed for ' ...
     'the Tercan current-limit mapping. STOP.']);

% -------------------------------------------------------------------------
% Published Tercan parameterization
% -------------------------------------------------------------------------

Imax_A = 120*ones(nBranch,1);

% First five feeder branches: 275 A
Imax_A(1:5) = 275;

% Current base
Ibase_A = ...
    cfg.baseMVA*1e6/(sqrt(3)*cfg.baseKV*1e3);

% Branch table
Branch = (1:nBranch).';
FromBus = branchData(:,1);
ToBus = branchData(:,2);

Tlimits = table( ...
    Branch, ...
    FromBus, ...
    ToBus, ...
    Imax_A);

writetable( ...
    Tlimits, ...
    'tercan_current_limits.csv');

%% ========================================================================
% 3. NOMINAL-VOLTAGE MVA EQUIVALENT
% Diagnostic only -- NOT used as a constraint
% ========================================================================

Iunique_A = sort(unique(Imax_A),'descend');

Nominal_MVA_equivalent = ...
    sqrt(3)*cfg.baseKV*1e3.*Iunique_A/1e6;

Tequiv = table( ...
    Iunique_A, ...
    Nominal_MVA_equivalent, ...
    'VariableNames', { ...
    'Published_current_limit_A', ...
    'Nominal_voltage_MVA_equivalent'});

writetable( ...
    Tequiv, ...
    'tercan_current_limit_nominal_MVA_equivalent.csv');

%% ========================================================================
% 4. CLEAN LOG
% ========================================================================

if exist('tercan_current_validation.log','file')
    delete('tercan_current_validation.log');
end

diary('tercan_current_validation.log');

cleanupDiary = onCleanup(@() diary('off')); %#ok<NASGU>

fprintf('============================================================\n');
fprintf('TERCAN EXTERNAL CURRENT-LIMIT VALIDATION\n');
fprintf('MATLAB: %s\n',version);
fprintf('Base: %.3f MVA, %.3f kV\n', ...
    cfg.baseMVA,cfg.baseKV);
fprintf('Vslack = %.6f pu\n', ...
    cfg.Vslack);
fprintf('BFS tol = %.3e pu | maxIter = %d\n', ...
    cfg.tol,cfg.maxIter);
fprintf('Ibase = %.9f A\n', ...
    Ibase_A);

fprintf('\nPublished external current limits:\n');
fprintf('  Branches 1-5  = 275 A\n');
fprintf('  Branches 6-32 = 120 A\n');

fprintf('\nNominal-voltage equivalents at %.2f kV:\n', ...
    cfg.baseKV);

for ii = 1:numel(Iunique_A)

    fprintf('  %.1f A -> %.6f MVA\n', ...
        Iunique_A(ii), ...
        Nominal_MVA_equivalent(ii));

end

fprintf('============================================================\n\n');

%% ========================================================================
% 5. GATE 0: UNMODIFIED BASE FEEDER
% ========================================================================

[Vb,Ib,~,infoB] = ...
    bfs_power_flow( ...
    busData0, ...
    branchData, ...
    cfg);

mBase = current_metric( ...
    Vb, ...
    Ib, ...
    branchData, ...
    Imax_A, ...
    Ibase_A, ...
    infoB);

fprintf('=== GATE 0: UNMODIFIED BASE FEEDER ===\n');

fprintf('Vmin       = %.9f pu\n', ...
    mBase.Vmin);

fprintf('Rmax       = %.9f\n', ...
    mBase.Rmax);

fprintf('Icrit      = %.6f A\n', ...
    mBase.Icrit_A);

fprintf('Ilimit     = %.6f A\n', ...
    mBase.Ilimit_A);

fprintf('CritBranch = %d-%d\n', ...
    mBase.critFrom, ...
    mBase.critTo);

fprintf('BFSres     = %.3e pu\n', ...
    mBase.BFSresidual);

baseFeasible = ...
    mBase.converged && ...
    mBase.Rmax <= 1 + tauI;

fprintf('Base current-feasible = %d\n\n', ...
    baseFeasible);

Tbase = table( ...
    mBase.Vmin, ...
    mBase.Rmax, ...
    mBase.Icrit_A, ...
    mBase.Ilimit_A, ...
    mBase.critFrom, ...
    mBase.critTo, ...
    mBase.BFSresidual, ...
    baseFeasible, ...
    'VariableNames', { ...
    'Vmin_pu', ...
    'Rmax', ...
    'Icrit_A', ...
    'Ilimit_A', ...
    'CritFrom', ...
    'CritTo', ...
    'BFS_residual_pu', ...
    'Current_feasible'});

writetable( ...
    Tbase, ...
    'tercan_current_base_check.csv');

%% ========================================================================
% 6. EIGHT EVCS CASES
% ========================================================================

Rows = {};
BusRows = {};

for ci = 1:numel(caseList)

    C = caseList(ci);

    ev = C.evcsBuses(:).';

    nE = numel(ev);

    Pev = ...
        cfg.Pinst_MW*C.lambda;

    ub = ...
        Pev*ones(nE,1);

    fprintf('\n');
    fprintf('============================================================\n');
    fprintf('CASE %s\n',C.name);
    fprintf('============================================================\n');

    %% --------------------------------------------------------------------
    % GATE 1A: NO BESS
    % ---------------------------------------------------------------------

    m0 = eval_alloc_current( ...
        zeros(nE,1), ...
        ev, ...
        C.lambda, ...
        busData0, ...
        branchData, ...
        cfg, ...
        Imax_A, ...
        Ibase_A);

    fprintf(['No BESS     : Rmax=%.9f | branch=%d-%d | ' ...
             'I=%.4f/%.1f A\n'], ...
        m0.Rmax, ...
        m0.critFrom, ...
        m0.critTo, ...
        m0.Icrit_A, ...
        m0.Ilimit_A);

    %% --------------------------------------------------------------------
    % GATE 1B: FULL ACTIVE COMPENSATION
    % ---------------------------------------------------------------------

    mf = eval_alloc_current( ...
        ub, ...
        ev, ...
        C.lambda, ...
        busData0, ...
        branchData, ...
        cfg, ...
        Imax_A, ...
        Ibase_A);

    fprintf(['Full comp   : Rmax=%.9f | branch=%d-%d | ' ...
             'I=%.4f/%.1f A\n'], ...
        mf.Rmax, ...
        mf.critFrom, ...
        mf.critTo, ...
        mf.Icrit_A, ...
        mf.Ilimit_A);

    %% --------------------------------------------------------------------
    % GATE 2: MINIMAX CURRENT-RATIO PROBLEM
    %
    % Determine the minimum achievable maximum normalized branch current:
    %
    %   min max_l |I_l| / I_l^max
    %
    % subject to:
    %
    %   0 <= P_BESS,j <= P_EVCS,j
    %
    % This determines whether ANY admissible active-only allocation
    % can satisfy the external current-limit set.
    % ---------------------------------------------------------------------

    MM = solve_minimax_current( ...
        ev, ...
        C.lambda, ...
        busData0, ...
        branchData, ...
        cfg, ...
        Imax_A, ...
        Ibase_A);

    fprintf(['Minimax     : Rmax=%.9f | Pdiag=%.6f kW | ' ...
             'branch=%d-%d | validStarts=%d | spread=%.3e\n'], ...
        MM.Rmax, ...
        sum(MM.xbest)*1000, ...
        MM.metric.critFrom, ...
        MM.metric.critTo, ...
        MM.nValidStarts, ...
        MM.Rspread);

    currentFeasible = ...
        MM.Rmax <= 1 + tauI;

    %% --------------------------------------------------------------------
    % GATE 3: MINIMUM BESS IF FEASIBLE
    % ---------------------------------------------------------------------

    if currentFeasible

        SZ = solve_minimum_bess_current( ...
            MM.xbest, ...
            ev, ...
            C.lambda, ...
            busData0, ...
            branchData, ...
            cfg, ...
            Imax_A, ...
            Ibase_A, ...
            tauI);

        Psize_kW = ...
            sum(SZ.xbest)*1000;

        mSelected = ...
            SZ.metric;

        nValidSizing = ...
            SZ.nValidStarts;

        sizingSpread_kW = ...
            SZ.objSpread_kW;

        status = ...
            "CURRENT-FEASIBLE WITH ACTIVE-ONLY BESS";

        xSizing = ...
            SZ.xbest;

        fprintf(['Sizing      : P=%.6f kW | Rmax=%.9f | ' ...
                 'branch=%d-%d | validStarts=%d | ' ...
                 'objSpread=%.6e kW\n'], ...
            Psize_kW, ...
            mSelected.Rmax, ...
            mSelected.critFrom, ...
            mSelected.critTo, ...
            nValidSizing, ...
            sizingSpread_kW);

    else

        Psize_kW = NaN;

        mSelected = ...
            MM.metric;

        nValidSizing = 0;

        sizingSpread_kW = NaN;

        status = ...
            "ACTIVE-ONLY CURRENT FEASIBILITY NOT ACHIEVABLE";

        xSizing = ...
            nan(nE,1);

        fprintf(['Verdict     : ACTIVE-ONLY CURRENT FEASIBILITY ' ...
                 'NOT ACHIEVABLE within ' ...
                 '0 <= P_BESS <= P_EVCS.\n']);

    end

    %% --------------------------------------------------------------------
    % FRESH REPLAY
    % ---------------------------------------------------------------------

    fprintf(['Fresh replay: Rmax=%.9f | Vmin=%.9f | ' ...
             'BFSres=%.3e\n'], ...
        mSelected.Rmax, ...
        mSelected.Vmin, ...
        mSelected.BFSresidual);

    %% --------------------------------------------------------------------
    % MASTER TABLE ROW
    % ---------------------------------------------------------------------

    Rows(end+1,:) = { ...
        string(C.name), ...
        m0.Rmax, ...
        sprintf('%d-%d',m0.critFrom,m0.critTo), ...
        m0.Icrit_A, ...
        m0.Ilimit_A, ...
        mf.Rmax, ...
        sprintf('%d-%d',mf.critFrom,mf.critTo), ...
        mf.Icrit_A, ...
        mf.Ilimit_A, ...
        MM.Rmax, ...
        sum(MM.xbest)*1000, ...
        sprintf('%d-%d', ...
            MM.metric.critFrom, ...
            MM.metric.critTo), ...
        MM.nValidStarts, ...
        MM.Rspread, ...
        currentFeasible, ...
        Psize_kW, ...
        mSelected.Rmax, ...
        sprintf('%d-%d', ...
            mSelected.critFrom, ...
            mSelected.critTo), ...
        mSelected.Vmin, ...
        mSelected.BFSresidual, ...
        nValidSizing, ...
        sizingSpread_kW, ...
        status}; %#ok<SAGROW>

    %% --------------------------------------------------------------------
    % BUS-WISE ALLOCATION
    % ---------------------------------------------------------------------

    for j = 1:nE

        BusRows(end+1,:) = { ...
            string(C.name), ...
            ev(j), ...
            MM.xbest(j)*1000, ...
            xSizing(j)*1000}; %#ok<SAGROW>

    end

end

%% ========================================================================
% 7. BUILD OUTPUT TABLES
% ========================================================================

T = cell2table( ...
    Rows, ...
    'VariableNames',{ ...
    'Case', ...
    'NoBESS_Rmax', ...
    'NoBESS_critical_branch', ...
    'NoBESS_Icrit_A', ...
    'NoBESS_Ilimit_A', ...
    'FullComp_Rmax', ...
    'FullComp_critical_branch', ...
    'FullComp_Icrit_A', ...
    'FullComp_Ilimit_A', ...
    'Minimax_Rmax', ...
    'Minimax_active_BESS_kW', ...
    'Minimax_critical_branch', ...
    'Minimax_valid_starts', ...
    'Minimax_Rspread', ...
    'Current_feasible', ...
    'Minimum_BESS_kW_if_feasible', ...
    'Selected_Rmax', ...
    'Selected_critical_branch', ...
    'Selected_Vmin_pu', ...
    'BFS_residual_pu', ...
    'Sizing_valid_starts', ...
    'Sizing_objective_spread_kW', ...
    'Status'});

Tbus = cell2table( ...
    BusRows, ...
    'VariableNames',{ ...
    'Case', ...
    'Bus', ...
    'Minimax_BESS_kW', ...
    'Sizing_BESS_kW_if_feasible'});

writetable( ...
    T, ...
    'tercan_current_validation_summary.csv');

writetable( ...
    Tbus, ...
    'tercan_current_validation_perbus.csv');

%% ========================================================================
% 8. SAVE COMPLETE EVIDENCE
% ========================================================================

save( ...
    'tercan_current_validation.mat', ...
    'T', ...
    'Tbus', ...
    'Tbase', ...
    'Tlimits', ...
    'Tequiv', ...
    'cfg', ...
    'caseList', ...
    'Imax_A', ...
    'Ibase_A', ...
    'baseFeasible', ...
    '-v7.3');

%% ========================================================================
% 9. FINAL DISPLAY
% ========================================================================

fprintf('\n');
fprintf('============================================================\n');
fprintf('FINAL TERCAN VALIDATION SUMMARY\n');
fprintf('============================================================\n');

disp(T);

fprintf('\nPublished limit set:\n');
disp(Tlimits);

fprintf('\nNominal-voltage MVA equivalents:\n');
disp(Tequiv);

fprintf('\nSaved:\n');
fprintf('  tercan_current_limits.csv\n');
fprintf('  tercan_current_limit_nominal_MVA_equivalent.csv\n');
fprintf('  tercan_current_base_check.csv\n');
fprintf('  tercan_current_validation_summary.csv\n');
fprintf('  tercan_current_validation_perbus.csv\n');
fprintf('  tercan_current_validation.mat\n');
fprintf('  tercan_current_validation.log\n');

fprintf('\nTERCAN CURRENT VALIDATION COMPLETED.\n');

%% ========================================================================
% LOCAL FUNCTIONS
% ========================================================================

function m = eval_alloc_current( ...
    x, ...
    ev, ...
    lambda, ...
    busData0, ...
    branchData, ...
    cfg, ...
    Imax_A, ...
    Ibase_A)

    bessMW = ...
        zeros(size(busData0,1),1);

    bessMW(ev) = ...
        x(:);

    bd = build_case_loads( ...
        busData0, ...
        ev, ...
        cfg.Pinst_MW, ...
        lambda, ...
        cfg.qFactorEVCS, ...
        bessMW, ...
        false);

    [V,Ibr,~,info] = ...
        bfs_power_flow( ...
        bd, ...
        branchData, ...
        cfg);

    m = current_metric( ...
        V, ...
        Ibr, ...
        branchData, ...
        Imax_A, ...
        Ibase_A, ...
        info);

end

function m = current_metric( ...
    V, ...
    Ibr, ...
    branchData, ...
    Imax_A, ...
    Ibase_A, ...
    info)

    IA = ...
        abs(Ibr(:))*Ibase_A;

    ratio = ...
        IA./Imax_A(:);

    [Rmax,idx] = ...
        max(ratio);

    m.converged = ...
        info.converged;

    m.BFSresidual = ...
        info.residual;

    m.Vmin = ...
        min(abs(V));

    m.I_A = ...
        IA;

    m.ratio = ...
        ratio;

    m.Rmax = ...
        Rmax;

    m.critIdx = ...
        idx;

    m.critFrom = ...
        branchData(idx,1);

    m.critTo = ...
        branchData(idx,2);

    m.Icrit_A = ...
        IA(idx);

    m.Ilimit_A = ...
        Imax_A(idx);

end

function OUT = solve_minimax_current( ...
    ev, ...
    lambda, ...
    busData0, ...
    branchData, ...
    cfg, ...
    Imax_A, ...
    Ibase_A)

    nE = ...
        numel(ev);

    Pev = ...
        cfg.Pinst_MW*lambda;

    lbx = ...
        zeros(nE,1);

    ubx = ...
        Pev*ones(nE,1);

    nStarts = ...
        cfg.nStarts;

    opts = optimoptions( ...
        'fmincon', ...
        'Algorithm','sqp', ...
        'Display','off', ...
        'SpecifyObjectiveGradient',true, ...
        'ConstraintTolerance',cfg.fminconConstrTol, ...
        'OptimalityTolerance',cfg.fminconOptTol, ...
        'StepTolerance',cfg.fminconStepTol, ...
        'MaxFunctionEvaluations',5000, ...
        'MaxIterations',1000);

    bestR = Inf;

    xbest = ...
        nan(nE,1);

    mbest = [];

    allR = ...
        nan(nStarts,1);

    allX = ...
        nan(nStarts,nE);

    for s = 1:nStarts

        if s == 1

            x0 = ubx;

        elseif s == 2

            x0 = 0.5*ubx;

        else

            x0 = ...
                ubx.*rand(nE,1);

        end

        m0 = eval_alloc_current( ...
            x0, ...
            ev, ...
            lambda, ...
            busData0, ...
            branchData, ...
            cfg, ...
            Imax_A, ...
            Ibase_A);

        gamma0 = ...
            m0.Rmax + 0.05;

        y0 = ...
            [x0; gamma0];

        lb = ...
            [lbx; 0];

        ub = ...
            [ubx; 10];

        [y,~,ef] = fmincon( ...
            @minimax_objective, ...
            y0, ...
            [],[],[],[], ...
            lb, ...
            ub, ...
            @(y) minimax_constraint( ...
                y, ...
                ev, ...
                lambda, ...
                busData0, ...
                branchData, ...
                cfg, ...
                Imax_A, ...
                Ibase_A), ...
            opts);

        x = ...
            y(1:nE);

        m = eval_alloc_current( ...
            x, ...
            ev, ...
            lambda, ...
            busData0, ...
            branchData, ...
            cfg, ...
            Imax_A, ...
            Ibase_A);

        if ef > 0 && m.converged

            allR(s) = ...
                m.Rmax;

            allX(s,:) = ...
                x(:).';

            if m.Rmax < bestR

                bestR = ...
                    m.Rmax;

                xbest = ...
                    x;

                mbest = ...
                    m;

            end

        end

    end

    valid = ...
        ~isnan(allR);

    if ~any(valid)

        error( ...
            'No successful minimax-current solution was obtained.');

    end

    OUT.Rmax = ...
        bestR;

    OUT.xbest = ...
        xbest;

    OUT.metric = ...
        mbest;

    OUT.nValidStarts = ...
        sum(valid);

    OUT.Rspread = ...
        max(allR(valid)) - min(allR(valid));

    OUT.allR = ...
        allR;

    OUT.allX = ...
        allX;

end

function [f,g] = minimax_objective(y)

    f = ...
        y(end);

    if nargout > 1

        g = ...
            zeros(numel(y),1);

        g(end) = ...
            1;

    end

end

function [c,ceq] = minimax_constraint( ...
    y, ...
    ev, ...
    lambda, ...
    busData0, ...
    branchData, ...
    cfg, ...
    Imax_A, ...
    Ibase_A)

    x = ...
        y(1:end-1);

    gamma = ...
        y(end);

    m = eval_alloc_current( ...
        x, ...
        ev, ...
        lambda, ...
        busData0, ...
        branchData, ...
        cfg, ...
        Imax_A, ...
        Ibase_A);

    c = ...
        m.ratio(:) - gamma;

    if ~m.converged

        c(:) = ...
            max(c(:),1);

    end

    ceq = [];

end

function OUT = solve_minimum_bess_current( ...
    xminimax, ...
    ev, ...
    lambda, ...
    busData0, ...
    branchData, ...
    cfg, ...
    Imax_A, ...
    Ibase_A, ...
    tauI)

    nE = ...
        numel(ev);

    Pev = ...
        cfg.Pinst_MW*lambda;

    lb = ...
        zeros(nE,1);

    ub = ...
        Pev*ones(nE,1);

    nStarts = ...
        cfg.nStarts;

    opts = optimoptions( ...
        'fmincon', ...
        'Algorithm','sqp', ...
        'Display','off', ...
        'SpecifyObjectiveGradient',true, ...
        'ConstraintTolerance',cfg.fminconConstrTol, ...
        'OptimalityTolerance',cfg.fminconOptTol, ...
        'StepTolerance',cfg.fminconStepTol, ...
        'MaxFunctionEvaluations',5000, ...
        'MaxIterations',1000);

    objs = ...
        nan(nStarts,1);

    allX = ...
        nan(nStarts,nE);

    bestObj = Inf;

    xbest = ...
        nan(nE,1);

    mbest = [];

    for s = 1:nStarts

        if s == 1

            x0 = ...
                xminimax;

        elseif s == 2

            x0 = ...
                ub;

        elseif s == 3

            x0 = ...
                0.5*(xminimax + ub);

        else

            x0 = ...
                ub.*rand(nE,1);

        end

        [x,~,ef] = fmincon( ...
            @sum_objective, ...
            x0, ...
            [],[],[],[], ...
            lb, ...
            ub, ...
            @(x) current_constraint( ...
                x, ...
                ev, ...
                lambda, ...
                busData0, ...
                branchData, ...
                cfg, ...
                Imax_A, ...
                Ibase_A), ...
            opts);

        m = eval_alloc_current( ...
            x, ...
            ev, ...
            lambda, ...
            busData0, ...
            branchData, ...
            cfg, ...
            Imax_A, ...
            Ibase_A);

        if ef > 0 && ...
                m.converged && ...
                m.Rmax <= 1 + tauI

            obj = ...
                sum(x);

            objs(s) = ...
                obj;

            allX(s,:) = ...
                x(:).';

            if obj < bestObj

                bestObj = ...
                    obj;

                xbest = ...
                    x;

                mbest = ...
                    m;

            end

        end

    end

    valid = ...
        ~isnan(objs);

    if ~any(valid)

        error( ...
            ['Minimax indicated current feasibility but minimum-BESS ' ...
             'optimization produced no accepted solution.']);

    end

    OUT.xbest = ...
        xbest;

    OUT.metric = ...
        mbest;

    OUT.nValidStarts = ...
        sum(valid);

    OUT.objSpread_kW = ...
        (max(objs(valid)) - min(objs(valid)))*1000;

    OUT.allObjectives_MW = ...
        objs;

    OUT.allX = ...
        allX;

end

function [f,g] = sum_objective(x)

    f = ...
        sum(x);

    if nargout > 1

        g = ...
            ones(numel(x),1);

    end

end

function [c,ceq] = current_constraint( ...
    x, ...
    ev, ...
    lambda, ...
    busData0, ...
    branchData, ...
    cfg, ...
    Imax_A, ...
    Ibase_A)

    m = eval_alloc_current( ...
        x, ...
        ev, ...
        lambda, ...
        busData0, ...
        branchData, ...
        cfg, ...
        Imax_A, ...
        Ibase_A);

    c = ...
        m.ratio(:) - 1;

    if ~m.converged

        c(:) = ...
            max(c(:),1);

    end

    ceq = [];

end