%% run_B4P_freeze.m
% Production-lineage MATLAB freeze for revised thermal-only B4-P.
%
% FIRST RUN:
%   RUN_STRESS_ONLY = true  -> P2/D4 only.
% If that passes, set false and run all eight cases.
%
% No B4-PQ, energy, or recharge calculations are executed here.

clear; clc;

RUN_STRESS_ONLY = false;  % <-- FIRST run: true. After P2/D4 passes, change to false.

assert(exist('fmincon','file') == 2, ...
    'fmincon not found. Optimization Toolbox is required.');

%% Exact physical/model configuration from production manuscript script
cfg.baseMVA = 100;
cfg.baseKV  = 12.66;
cfg.Vslack  = 1.05;

cfg.Vthr = 0.95;   % not used in B4-P sizing
cfg.Lthr = 100;

cfg.Smax_branch = [
  6.0; 5.0; 4.0; 4.0; 3.5; 3.5; 3.0; 3.0;
  3.0; 3.0; 2.5; 2.5; 2.5; 2.5; 2.0; 2.0;
  2.0; 4.0; 3.5; 3.0; 3.0; 3.5; 3.0; 2.5;
  3.5; 3.0; 2.5; 2.5; 2.5; 2.0; 2.0; 2.0
];

cfg.Pinst_MW = 0.15;
cfg.pfEVCS = 0.95;
cfg.qFactorEVCS = tan(acos(cfg.pfEVCS));

% Production script used 1e-5 pu and maxIter=50.
cfg.productionTol = 1e-5;
cfg.productionMaxIter = 50;

% Canonical numerical freeze uses the SAME BFS equations, but a tighter
% convergence tolerance so boundary residuals are not hidden by the original
% 1e-5 stopping threshold.
cfg.tol = 1e-12;
cfg.maxIter = 200;

cfg.tauL_pct = 1e-6;
cfg.nStarts = 16;
cfg.fminconConstrTol = 1e-9;
cfg.fminconOptTol = 1e-9;
cfg.fminconStepTol = 1e-12;

[busData0, branchData] = ieee33_data();

%% ------------------------------------------------------------------------
% Gate A: production-physics anchor replay at ORIGINAL production BFS tol
% -------------------------------------------------------------------------
cfgAnchor = cfg;
cfgAnchor.tol = cfg.productionTol;
cfgAnchor.maxIter = cfg.productionMaxIter;

[Vb, Ib, Sb, infob] = bfs_power_flow(busData0, branchData, cfgAnchor);
mb = compute_metrics(Vb, Ib, Sb, branchData, cfgAnchor, infob);

P2 = [14 16 17 18 30 33];
bessZero = zeros(33,1);
bdStress = build_case_loads(busData0, P2, cfg.Pinst_MW, 1.6, ...
    cfg.qFactorEVCS, bessZero, false);
[Vs, Is, Ss, infos] = bfs_power_flow(bdStress, branchData, cfgAnchor);
ms = compute_metrics(Vs, Is, Ss, branchData, cfgAnchor, infos);

fprintf('\n=== GATE A: PRODUCTION-PHYSICS ANCHORS (original BFS tol = %.1e) ===\n', cfgAnchor.tol);
fprintf('Base    : Vmin=%.9f | Lmax=%.9f%% | Ploss=%.6f kW | BFSres=%.3e\n', ...
    mb.Vmin, mb.LmaxPct, mb.Ploss_kW, mb.BFSresidual);
fprintf('P2/D4-0 : Vmin=%.9f | Lmax=%.9f%% | Ploss=%.6f kW | BFSres=%.3e\n', ...
    ms.Vmin, ms.LmaxPct, ms.Ploss_kW, ms.BFSresidual);

% Exact anchors generated by the supplied production equations/data.
refBase = [0.9591495598, 81.5340281190, 188.467135479];
refP2D4 = [0.8495567397, 126.871264608, 570.080339724];

anchorErr = max(abs([mb.Vmin-refBase(1), ...
                     mb.LmaxPct-refBase(2), ...
                     mb.Ploss_kW-refBase(3), ...
                     ms.Vmin-refP2D4(1), ...
                     ms.LmaxPct-refP2D4(2), ...
                     ms.Ploss_kW-refP2D4(3)]));

if anchorErr > 1e-3
    error(['Gate A FAILED: production-physics anchors do not reproduce. ' ...
           'Do not run optimization until data/config/sign conventions are reconciled.']);
end

fprintf('GATE A: PASS\n');

%% ------------------------------------------------------------------------
% Gate B/C: centralized thermal-only B4-P
% -------------------------------------------------------------------------
P1 = [6 10 14 18 22 26];
lam = struct('D1',0.6,'D2',1.0,'D3',1.3,'D4',1.6);

if RUN_STRESS_ONLY
    defs = {'P2/D4', P2, lam.D4};
    modeName = 'P2D4';
else
    defs = { ...
        'P1/D1',P1,lam.D1;
        'P1/D2',P1,lam.D2;
        'P1/D3',P1,lam.D3;
        'P1/D4',P1,lam.D4;
        'P2/D1',P2,lam.D1;
        'P2/D2',P2,lam.D2;
        'P2/D3',P2,lam.D3;
        'P2/D4',P2,lam.D4};
    modeName = 'FULL';
end

caseList = struct('name',{},'evcsBuses',{},'lambda',{});
for i = 1:size(defs,1)
    caseList(i) = struct('name',defs{i,1}, ...
        'evcsBuses',defs{i,2},'lambda',defs{i,3});
end

logName = sprintf('B4P_%s_freeze_log.txt',modeName);
diary(logName);

fprintf('\nCanonical BFS tol = %.3e pu\n', cfg.tol);
fprintf('Thermal feasibility tolerance = %.3e %%\n', cfg.tauL_pct);

results = centralized_thermal_B4P(busData0, branchData, cfg, caseList);

%% Archive raw results without rounding
if RUN_STRESS_ONLY
    matName = 'B4P_P2D4_freeze.mat';
else
    matName = 'B4P_canonical_freeze.mat';
end
save(matName,'results','cfg','caseList','mb','ms','-v7.3');

%% Scalar audit CSV
n = numel(results);
Case = strings(n,1);
P_BESS_total_kW = zeros(n,1);
Lmax_pct = zeros(n,1);
loadingResidual_pct = zeros(n,1);
Vmin_pu = zeros(n,1);
BFS_residual_pu = zeros(n,1);
BFS_iters = zeros(n,1);
exitflag = nan(n,1);
firstorderopt = nan(n,1);
fminconConstrViolation = nan(n,1);
iterations = nan(n,1);
funcCount = nan(n,1);
nValidStarts = zeros(n,1);
objSpread_kW = zeros(n,1);
allocSpread_kW = zeros(n,1);
critFrom = zeros(n,1);
critTo = zeros(n,1);
Class = strings(n,1);

for k = 1:n
    r = results(k);
    Case(k) = string(r.name);
    P_BESS_total_kW(k) = r.P_BESS_total_kW;
    Lmax_pct(k) = r.Lmax_pct;
    loadingResidual_pct(k) = r.loadingResidual_pct;
    Vmin_pu(k) = r.Vmin;
    BFS_residual_pu(k) = r.BFS_residual_pu;
    BFS_iters(k) = r.BFS_iters;
    exitflag(k) = r.exitflag;
    firstorderopt(k) = r.firstorderopt;
    fminconConstrViolation(k) = r.fminconConstrViolation;
    iterations(k) = r.iterations;
    funcCount(k) = r.funcCount;
    nValidStarts(k) = r.nValidStarts;
    objSpread_kW(k) = r.objSpread_kW;
    allocSpread_kW(k) = r.allocSpread_kW;
    critFrom(k) = r.critFrom;
    critTo(k) = r.critTo;
    Class(k) = string(r.class);
end

T = table(Case,P_BESS_total_kW,Lmax_pct,loadingResidual_pct,Vmin_pu, ...
    BFS_residual_pu,BFS_iters,exitflag,firstorderopt,fminconConstrViolation, ...
    iterations,funcCount,nValidStarts,objSpread_kW,allocSpread_kW, ...
    critFrom,critTo,Class);

csvName = sprintf('B4P_%s_freeze_summary.csv',modeName);
writetable(T,csvName);
disp(T);

%% Bus-level allocation text
allocName = sprintf('B4P_%s_allocations.txt',modeName);
fid = fopen(allocName,'w');
for k = 1:n
    fprintf(fid,'\n%s\n',results(k).name);
    fprintf(fid,'Bus     BESS_kW\n');
    for j = 1:numel(results(k).evcsBuses)
        fprintf(fid,'%3d   %12.6f\n', ...
            results(k).evcsBuses(j),results(k).alloc_kW(j));
    end
end
fclose(fid);

fprintf('\nSaved:\n  %s\n  %s\n  %s\n', matName, logName, csvName);
fprintf('  %s\n', allocName);

diary off;
